export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_SIDEBAR = "CHANGE_SIDEBAR";
export const ADD_MOVIE_BEGIN = "ADD_MOVIE_BEGIN";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
