export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_SIDEBAR = "CHANGE_SIDEBAR";

export const ADD_MOVIE_BEGIN = "ADD_MOVIE_BEGIN";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";

export const GET_FRIENDS_BEGIN = "GET_FRIENDS_BEGING";
export const GET_FRIENDS_SUCCESS = "GET_FREINDS_SUCCESS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";

export const ADD_FRIEND_BEGIN = "ADD_FRIEND_BEGIN";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR";

export const DELETE_FRIEND_BEGIN = "DELETE_FRIEND_BEGIN";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_ERROR = "DELETE_FRIEND_ERROR";

export const GET_WATCHLIST_BEGIN = "GET_WATCHLIST_BEGIN";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_ERROR = "GET_WATCHLIST_ERROR";

export const GET_TIERLIST_BEGIN = "GET_TIERLIST_BEGIN";
export const GET_TIERLIST_SUCCESS = "GET_TIERLIST_SUCCESS";
export const GET_TIERLIST_ERROR = "GET_TIERLIST_ERROR";

export const FAVORITE_MOVIE_SUCCESS = "FAVORITE_MOVIE_SUCCESS";
export const FAVORITE_MOVIE_ERROR = "FAVORITE_MOVIE_ERROR";

export const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
export const RATE_MOVIE_ERROR = "RATE_MOVIE_ERROR";

export const OPEN_RATING_MODAL = "OPEN_RATING_MODEL";

export const CLOSE_RATING_MODAL = "CLOSE_RATING_MODAL";

export const OPEN_ERROR_SNACKBAR = "OPEN_ERROR_SNACKBAR";
export const CLOSE_ERROR_SNACKBAR = "CLOSE_ERROR_SNACKBAR";

export const GET_FRIEND_WATCHLIST_BEGIN = "GET_FREIND_WATCHLIST_BEGIN";
export const GET_FRIEND_WATCHLIST_SUCCESS = "GET_FREIND_WATCHLIST_SUCCESS";
export const GET_FRIEND_WATCHLIST_ERROR = "GET_FREIND_WATCHLIST_ERROR";

export const GET_FRIEND_SUCCESS = "GET_FRIEND_BEGIN";
export const GET_FRIEND_ERROR = "GET_FRIEND_SUCCESS";
export const GET_FRIEND_BEGIN = "GET_FRIEND_ERROR";

export const GET_FRIEND_TIERLIST_BEGIN = "GET_FRIEND_TIERLIST_BEGIN";
export const GET_FRIEND_TIERLIST_SUCCESS = "GET_FRIEND_TIERLIST_SUCCESS";
export const GET_FRIEND_TIERLIST_ERROR = "GET_FRIEND_TIERLIST_ERROR";

export const OPEN_SEARCH_BAR = "OPEN_SEARCH_BAR";
export const CLOSE_SEARCH_BAR = "CLOSE_SEARCH_BAR";

export const FIND_FRIENDS_SUCCESS = "FIND_FRIENDS_SUCCESS";
export const FIND_FRIENDS_ERROR = "FIND_FREINDS_ERROR";
